---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
