#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

REBASE_PATH="$(git rev-parse --git-path rebase-merge)" # directory
MERGE_PATH="$(git rev-parse --git-path MERGE_HEAD)"    # file

# Check if the rebase or merge path exists.
if [ -d "$REBASE_PATH" ] || [ -f "$MERGE_PATH" ]; then
  echo "Skipping Husky pre-commit hook: rebase or merge detected."
else
  echo "Running Husky pre-commit hook."
  dotnet husky run 
fi
