name: CI-macOS

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*

jobs:
  macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Enable Unity Cache Support
      id: cache-unity
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-unityfull
        path: Unity

    - name: Download Unity 2018 LTS
      if: steps.cache-unity.outputs.cache-hit != 'true'
      run: curl -o ./unity.pkg -k https://download.unity3d.com/download_unity/05119b33d0b7/MacEditorInstaller/Unity.pkg

    - name: Install Unity
      if: steps.cache-unity.outputs.cache-hit != 'true'
      run: sudo installer -package unity.pkg -target /

    - name: Prepare Cache
      if: steps.cache-unity.outputs.cache-hit != 'true'
      run: sudo ditto /Applications/Unity/ Unity
            
    - name: Restore Cache
      if: steps.cache-unity.outputs.cache-hit == 'true'
      run: sudo ditto Unity/ /Applications/Unity/

    - name: Test
      run: dotnet test -c Debug ./src/Microsoft.Unity.Analyzers.Tests
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
