name: CI-macOS

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*

jobs:
  macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1

    # So far we only need managed assemblies for testing
    # We don't need to download/install Unity every run, we just need to cache those managed assemblies
    # But we have to deal with the following:
    # - the cache only works under the GITHUB_WORKSPACE folder (so we cannot cache /Applications/Unity/Unity.app/Contents)
    # - the cache is linited to 400M per run (so we cannot cache the full Unity installation)
    # - When Unity is not installed, our detection logic will fallback to /Applications/Unity/Unity.app/Contents
    - name: Enable Unity Cache Support
      id: cache-unity
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-unity
        path: Managed

    - name: Download Unity 2018 LTS
      if: steps.cache-unity.outputs.cache-hit != 'true'
      run: curl -o ./unity.pkg -k https://download.unity3d.com/download_unity/05119b33d0b7/MacEditorInstaller/Unity.pkg

    - name: Install Unity
      if: steps.cache-unity.outputs.cache-hit != 'true'
      run: sudo installer -package unity.pkg -target /

    - name: Prepare Cache
      if: steps.cache-unity.outputs.cache-hit != 'true'
      run: sudo ditto /Applications/Unity/Unity.app/Contents/Managed/ Managed
            
    - name: Restore Cache
      if: steps.cache-unity.outputs.cache-hit == 'true'
      run: sudo ditto Managed/ /Applications/Unity/Unity.app/Contents/Managed/

    - name: Test
      run: dotnet test -c Debug ./src/Microsoft.Unity.Analyzers.Tests
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
