name: CI-macOS

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

jobs:
  macos:
    runs-on: macos-latest
    permissions:
      actions: read
      contents: read
      deployments: read
      packages: none
      pull-requests: write
      security-events: write

    steps:
    - name: Checkout 
      uses: actions/checkout@v1

    - name: Set Environment Variables
      uses: ./.github/actions/setvars
      with:
        varFilePath: ./.github/variables/unity.env

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: false

    - name: Download Unity
      run: curl -o ./unity.pkg -k https://download.unity3d.com/download_unity/${{ env.UNITY_HASH }}/MacEditorInstaller/Unity.pkg

    - name: Install Unity
      run: sudo installer -package unity.pkg -target /

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2

    - name: Build
      run: dotnet build -c Debug ./src/Microsoft.Unity.Analyzers.sln /p:UseSharedCompilation=false
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_NOLOGO: 1
          
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      
    - name: Test context (main)
      if: github.ref == 'refs/heads/main'
      run: echo "TEST_FILTER=." >> $GITHUB_ENV
    
    - name: Test context (feature)    
      if: github.ref != 'refs/heads/main'
      run: echo "TEST_FILTER=FullyQualifiedName!~ConsistencyTests" >> $GITHUB_ENV

    - name: Test
      run: dotnet test -c Debug ./src/Microsoft.Unity.Analyzers.Tests --filter ${{env.TEST_FILTER}}
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_NOLOGO: 1
